name: Playwright Tests

on:
  schedule:
    - cron: '*/30 * * * *'   # Every 30 minutes
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Start your Vite dev server in background
      - name: Start app server in background
        run: npm run dev &

      # Wait until your app is ready to accept connections
      - name: Wait for app server to be ready
        run: npx wait-on http://localhost:5173

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test tests/tests

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: traces
          path: test-results/

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: test-results/screenshots/

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos
          path: test-results/videos/
      - name: Upload Logs
        uses: actions/upload-artifact@v4  